# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: Format

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format-14
        run: sudo apt-get install clang-format-14
      - uses: rhaschke/pre-commit-action@main
        id: precommit
      - name: Upload pre-commit changes
        if: failure() && steps.precommit.outcome == 'failure'
        uses: rhaschke/upload-git-patch-action@main
        with:
          name: pre-commit
